resources:
- ./infra/deployment.yaml
- ./infra/hpa.yaml
- ./infra/namespaces.yaml
- ./infra/service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 566034038752.dkr.ecr.ap-northeast-2.amazonaws.com/awsome-flux-example
  newTag: latest
