apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-infra
  namespace: gitops-sample
spec:
  selector:
    matchLabels:
      run: fleet-infra
  replicas: 1
  template:
    metadata:
      labels:
        run: fleet-infra
    spec:
      containers:
      - name: fleet-infra
        image: 566034038752.dkr.ecr.ap-northeast-2.amazonaws.com/awsome-flux-example
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

