apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fleet-infra-app
  name: fleet-infra-app
  namespace: gitops-sample
spec:
  selector:
    matchLabels:
      app: fleet-infra-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fleet-infra-app
    spec:
      containers:
      - image: 566034038752.dkr.ecr.ap-northeast-2.amazonaws.com/awsome-flux-example
        imagePullPolicy: Always
        name: fleet-infra-app
        ports:
        - containerPort: 8080
          protocol: TCP
