apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: member-service
  name: member-service
  namespace: member-service
spec:
  selector:
    matchLabels:
      app: member-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
      - image: 300728852453.dkr.ecr.us-west-2.amazonaws.com/tenducks/member-service:latest
        imagePullPolicy: Always
        name: member-service
        ports:
        - containerPort: 80
          protocol: TCP
