apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: member-service
spec:
  selector:
    app: member-service
  type: LoadBalancer  
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
