apiVersion: v1
kind: Service
metadata:
  name: fleet-infra
  namespace: gitops-sample
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"  
spec:
  selector:
     app: demo-flask-backend
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080