apiVersion: v1
kind: Service
metadata:
  name: fleet-infra-svc
  namespace: gitops-sample
spec:
  selector:
    app: fleet-infra-app
  type: LoadBalancer  
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080
