apiVersion: v1
kind: Service
metadata:
  name: fleet-infra
  namespace: gitops-sample
  labels:
    run: fleet-infra
spec:
  selector:
     app: demo-flask-backend
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080